
//! Autogenerated weights for `pallet_move`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-05-21, STEPS: `100`, REPEAT: `25`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `EQML220902-02`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --pallet
// pallet-move
// --extrinsic
// *
// --steps
// 100
// --repeat
// 25
// --output
// weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_move`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::weight_info::WeightInfo for SubstrateWeight<T> {
	/// Storage: `MoveModule::MultisigStorage` (r:1 w:1)
	/// Proof: `MoveModule::MultisigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:3 w:3)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:3 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:4 w:4)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MoveModule::VMStorage` (r:2 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 9]`.
	fn execute(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9476`
		//  Estimated: `17303 + n * (1491 ±8)`
		// Minimum execution time: 33_000_000 picoseconds.
		Weight::from_parts(35_000_000, 0)
			.saturating_add(Weight::from_parts(0, 17303))
			// Standard Error: 192_486_421
			.saturating_add(Weight::from_parts(5_799_434_900, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 1491).saturating_mul(n.into()))
	}
	/// Storage: `MoveModule::VMStorage` (r:1 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 2]`.
	fn publish_module(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7796`
		//  Estimated: `13927`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(310_580_327, 0)
			.saturating_add(Weight::from_parts(0, 13927))
			// Standard Error: 1_786_407
			.saturating_add(Weight::from_parts(19_643_866, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `MoveModule::VMStorage` (r:1 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 2]`.
	fn publish_module_bundle(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7796`
		//  Estimated: `13927`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(312_612_550, 0)
			.saturating_add(Weight::from_parts(0, 13927))
			// Standard Error: 2_014_955
			.saturating_add(Weight::from_parts(38_749_744, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `MoveModule::VMStorage` (r:1 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_stdlib_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7796`
		//  Estimated: `11261`
		// Minimum execution time: 204_000_000 picoseconds.
		Weight::from_parts(218_000_000, 0)
			.saturating_add(Weight::from_parts(0, 11261))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
