
//! Autogenerated weights for `pallet_move`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-04-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `michaelardtsMBP`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --pallet
// pallet-move
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_move`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::weight_info::WeightInfo for WeightInfo<T> {
	/// Storage: `MoveModule::MultisigStorage` (r:1 w:1)
	/// Proof: `MoveModule::MultisigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MoveModule::ChoreOnIdleStorage` (r:1 w:1)
	/// Proof: `MoveModule::ChoreOnIdleStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MoveModule::VMStorage` (r:3 w:2)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 7]`.
	fn execute(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8700`
		//  Estimated: `14577 + n * (812 ±0)`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(552_887_566, 0)
			.saturating_add(Weight::from_parts(0, 14577))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 812).saturating_mul(n.into()))
	}
	/// Storage: `MoveModule::VMStorage` (r:2 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 3]`.
	fn publish_module(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `111 + n * (3506 ±0)`
		//  Estimated: `2180 + n * (4531 ±116)`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(25_415_305, 0)
			.saturating_add(Weight::from_parts(0, 2180))
			// Standard Error: 1_274_995
			.saturating_add(Weight::from_parts(132_265_386, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 4531).saturating_mul(n.into()))
	}
	/// Storage: `MoveModule::VMStorage` (r:1 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn publish_module_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `111`
		//  Estimated: `3576`
		// Minimum execution time: 161_000_000 picoseconds.
		Weight::from_parts(168_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3576))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `MoveModule::VMStorage` (r:1 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_stdlib_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7123`
		//  Estimated: `10588`
		// Minimum execution time: 197_000_000 picoseconds.
		Weight::from_parts(201_000_000, 0)
			.saturating_add(Weight::from_parts(0, 10588))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl crate::weight_info::WeightInfo for () {
	/// Storage: `MoveModule::MultisigStorage` (r:1 w:1)
	/// Proof: `MoveModule::MultisigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MoveModule::ChoreOnIdleStorage` (r:1 w:1)
	/// Proof: `MoveModule::ChoreOnIdleStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MoveModule::VMStorage` (r:3 w:2)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 7]`.
	fn execute(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8700`
		//  Estimated: `14577 + n * (812 ±0)`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(552_887_566, 0)
			.saturating_add(Weight::from_parts(0, 14577))
			.saturating_add(Weight::from_parts(0, 812).saturating_mul(n.into()))
	}
	/// Storage: `MoveModule::VMStorage` (r:2 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 3]`.
	fn publish_module(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `111 + n * (3506 ±0)`
		//  Estimated: `2180 + n * (4531 ±116)`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(25_415_305, 0)
			.saturating_add(Weight::from_parts(0, 2180))
			// Standard Error: 1_274_995
			.saturating_add(Weight::from_parts(132_265_386, 0).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 4531).saturating_mul(n.into()))
	}
	/// Storage: `MoveModule::VMStorage` (r:1 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn publish_module_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `111`
		//  Estimated: `3576`
		// Minimum execution time: 161_000_000 picoseconds.
		Weight::from_parts(168_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3576))
	}
	/// Storage: `MoveModule::VMStorage` (r:1 w:1)
	/// Proof: `MoveModule::VMStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_stdlib_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7123`
		//  Estimated: `10588`
		// Minimum execution time: 197_000_000 picoseconds.
		Weight::from_parts(201_000_000, 0)
			.saturating_add(Weight::from_parts(0, 10588))
	}
}
