
//! Autogenerated weights for substrate_movevm_pallet
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-07-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Optimus-ROG`, CPU: `12th Gen Intel(R) Core(TM) i9-12950HX`
//! EXECUTION: `Some(Wasm)`, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// substrate_movevm_pallet
// --steps=50
// --repeat=20
// --execution=wasm
// --wasm-execution=compiled
// --output
// ../substrate-movevm-pallet/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs
// --extrinsic
// *

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for substrate_movevm_pallet.
pub trait WeightInfo {
	fn execute() -> Weight;
}

/// Weights for substrate_movevm_pallet using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn execute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_552_000 picoseconds.
		Weight::from_parts(6_835_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn execute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_552_000 picoseconds.
		Weight::from_parts(6_835_000, 0)
	}
}
