name: Format and lint

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.toml"
      - "rpc/**"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run fmt and clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all-targets -- -D warnings

      # You can edit this part when you add tests
      # - name: Test
      #   run: cargo test --verbose
